# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PythonPackage

on:
    push:
        branches: [ main, develop ]
        tags:
            - '*'

    pull_request:
        branches: [ main, develop ]

jobs:
    build:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.6, 3.7, 3.8, 3.9]

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements_dev.txt
                  python setup.py install
            - name: Sort imports with isort
              run: |
                  isort csvjson tests
            - name: Format code with black
              run: |
                  black csvjson tests
            - name: Lint with flake8
              run: |
                  flake8 csvjson tests
            - name: Test with pytest
              run: |
                  pytest tests --cov=csvjson
            - name: Test with doctest
              run: |
                  pytest --doctest-modules csvjson
            - name: Static typechecking with mypy
              run: |
                  mypy csvjson tests
